version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./sentrifugo:/var/www/html/sentrifugo
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: hrdb
      MYSQL_USER: hr_user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
